{"name": "Test01: Verify Invalid Login to Parabank", "status": "passed", "description": "This test verifies that attempting to log in with invalid credentials results in error message.", "parameters": [{"name": "user", "value": "'nir'"}, {"name": "password", "value": "'12344'"}], "start": 1725091910620, "stop": 1725091912346, "uuid": "32c12542-bf2a-4f11-ae7c-b471c4f4256d", "historyId": "53491008fb1b3f95ae5b5cc4f02f911d", "testCaseId": "c01495944366ff1e48ce06d760bf062a", "fullName": "test_web.TestWeb#test_verify_login_error_parabank", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "DESKTOP-DHGB96Q"}, {"name": "thread", "value": "5104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_web"}]}