{"name": "Test01: Verify Invalid Login to Parabank", "status": "passed", "description": "This test verifies that attempting to log in with invalid credentials results in error message.", "parameters": [{"name": "user", "value": "'dafna'"}, {"name": "password", "value": "'12342'"}], "start": 1725091912915, "stop": 1725091914045, "uuid": "ad06f5cc-5b55-428b-8c55-f74e0e1608da", "historyId": "e1358381c7a936f305ea0a93a563b12f", "testCaseId": "c01495944366ff1e48ce06d760bf062a", "fullName": "test_web.TestWeb#test_verify_login_error_parabank", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('init_web_driver')"}, {"name": "suite", "value": "test_web"}, {"name": "subSuite", "value": "TestWeb"}, {"name": "host", "value": "DESKTOP-DHGB96Q"}, {"name": "thread", "value": "5104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_web"}]}